### ISSUE TITLE
Current status, and potential google.cloud.datastore support?

### ISSUE THREAD

**Issue by mikelambert** [lucemia/gcloud-python-orm#3]
I just discovered this library, and seems like something I've been meaning (and procrastinating) on building myself. (Migrating from GAE Managed to GAE Flexible, trying to get off DB/NDB into google.cloud.datastore so I can use it from Dataflow, etc)

Are you still using this code? I see the open issue on `gcloud` 0.4 support (and I'd need to migrate to `google.cloud.datastore` as well), so I kind of suspect this project is kind of dead...but curious to hear more, understand what's up, see if you'd accept patches to get it on `google.cloud.datastore`, etc. Thanks!

**Comment by lucemia** [comment]
I am not using this library now. You can use the code / patch it / or create your own version.  :)
If your patch is tested, I will accept the PR. 

There is a pull request 0.4 from https://github.com/lucemia/gcloud-python-orm/pull/1 
The reason I didn't merge that PR is because that model is more like django but mine is more like appengine. I cannot change my interface at that moment. It is not an issue for me anymore.

Another issue is gcloud interface changed too often at that moments, so I don't want to put any effect on that. Hope it is better now.
